/**
 * This code was generated by Builder.io
 */
import React from "react";

interface PartnerItemProps {
  imageSrc: string;
  name: string;
}

const PartnerItem: React.FC<PartnerItemProps> = ({ imageSrc, name }) => {
  return (
    <div className="flex flex-wrap gap-6 mt-9 w-full whitespace-nowrap max-md:max-w-full">
      <img
        loading="lazy"
        src={imageSrc}
        alt={`${name} logo`}
        className="object-contain shrink-0 my-auto aspect-[1.96] w-[114px]"
      />
      <div className="flex-1 shrink basis-0 max-md:max-w-full">{name}</div>
    </div>
  );
};

export default PartnerItem;
