/**
 * This code was generated by Builder.io
 */
import React from "react";
import Heading from "../Heading";
import { cn } from "@/utils/styles";

export type CalloutProps = {
  title: string;
  description?: string[];
  theme: string;
};

const Callout: React.FC<CalloutProps> = ({ title, description, theme }) => {
  return (
    <div
      className={cn("flex flex-col mt-32 font-medium w-full", {
        "text-white": theme === "dark" || theme === "blue",
        "text-black": theme === "light",
      })}
    >
      <Heading theme={theme} headerTag="h1">
        {title}
      </Heading>
      {description?.map((item) => (
        <p key={item} className="mt-12 text-xl w-full italic">
          {item}
        </p>
      ))}
    </div>
  );
};

export default Callout;
