/**
 * This code was generated by Builder.io
 */
import React from "react";

export interface CalloutProps {
  title: string;
  description?: string;
}

const Callout: React.FC<CalloutProps> = (props) => {
  return (
    <div className="flex flex-col grow shrink font-medium min-w-[240px] w-[592px] max-md:max-w-full">
      <h2 className="text-8xl max-md:max-w-full max-md:text-4xl">
        {props.title}
      </h2>
      {props.description && (
        <p className="mt-12 text-3xl max-md:mt-10 max-md:max-w-full">
          {props.description}
        </p>
      )}
    </div>
  );
};

export default Callout;
