/**
 * This code was generated by Builder.io
 */
import React from "react";
import Image from "next/image";
import LanguageSelector from "./LanguageSelector";

export interface HeaderProps {
  logo: {
    src: string;
    alt: string;
  };
  title: string;
  navItems: Array<{
    text: string;
    href: string;
  }>;
  languages: Array<{
    code: string;
    name: string;
  }>;
}

const Header: React.FC<HeaderProps> = (props) => {
  return (
    <header className="flex flex-wrap gap-10 items-end text-2xl min-w-[240px] max-md:max-w-full">
      <Image
        src={props.logo.src}
        alt={props.logo.alt}
        width={496}
        height={97}
        className="object-contain aspect-[5.1] min-w-[240px] w-[496px] max-md:max-w-full"
      />
      <h1 className="max-md:max-w-full">{props.title}</h1>
      <nav>
        <ul className="flex gap-4">
          {props.navItems.map((item, index) => (
            <li key={`${item.href}_${index}`}>
              <a href={item.href} className="text-4xl text-slate-50">
                {item.text}
              </a>
            </li>
          ))}
        </ul>
      </nav>
      <LanguageSelector languages={props.languages} />
    </header>
  );
};

export default Header;
