/**
 * This code was generated by Builder.io
 */
import React from "react";
import Header, { HeaderProps } from "./Header";
import Callout, { CalloutProps } from "./Callout";

type HeroBannerProps = {
  header: HeaderProps;
  callout: CalloutProps;
};

const HeroBanner: React.FC<HeroBannerProps> = (props) => {
  return (
    <section className="flex flex-wrap gap-36 items-start px-36 pt-20 pb-96 text-white max-md:px-5 max-md:pb-24">
      <Header {...props.header} />
      <Callout {...props.callout} />
    </section>
  );
};

export default HeroBanner;
