/**
 * This code was generated by Builder.io
 */
export const CityKeyData = {
  backgroundImage:
    "https://cdn.builder.io/api/v1/image/assets/TEMP/3905c00aeeb644a7cacbef99d0c8314f4d9d8c076dffbdaeb405ab792760e735?placeholderIfAbsent=true&apiKey=82eec9096df64eb8b436c0dc64d15566",
  title: "CityKey",
  description:
    "The CityKey MasterCard provides you an immediate access to all benefits assigned by your Municipality, University or participating Merchant.",
  logoImage:
    "https://cdn.builder.io/api/v1/image/assets/TEMP/b46131e26fd8e9023318180a38d70b2896232cfbfe8a850bee53be495db81fae?placeholderIfAbsent=true&apiKey=82eec9096df64eb8b436c0dc64d15566",
  cardImage:
    "https://cdn.builder.io/api/v1/image/assets/TEMP/11ef8723536917b69ae8ecc6a454170c2178bc6cb7b7faa54bba42169a2aafd0?placeholderIfAbsent=true&apiKey=82eec9096df64eb8b436c0dc64d15566",
  moreIcon:
    "https://cdn.builder.io/api/v1/image/assets/TEMP/98a785c1141e28912fe905c131c5806daaa6eb55493fd9486ac0c7a8c1310b68?placeholderIfAbsent=true&apiKey=82eec9096df64eb8b436c0dc64d15566",
  moreText: "More",
  moreLink: "/more",
};
