/**
 * This code was generated by Builder.io
 */
import React from "react";
import Checkmark from "./Icons/Checkmark";

type BenefitListProps = {
  benefits: string[];
};

const BenefitList: React.FC<BenefitListProps> = ({ benefits }) => {
  return (
    <ul className="pl-16 flex flex-col items-start mt-10 w-full md:mt-20">
      {benefits.map((benefit, index) => (
        <li
          key={`${benefit}_${index}`}
          className="inline-flex items-start mt-8 max-w-full first:mt-0 gap-6"
        >
          <Checkmark className="flex-shrink-0 mt-0.5" />
          <span className="break-words italic">{benefit}</span>
        </li>
      ))}
    </ul>
  );
};

export default BenefitList;
