/**
 * This code was generated by Builder.io
 */
import React from "react";
import OurPartners from "./OurPartners/OurPartners";
import InstantAccess from "./InstantAccess/InstantAccess";

const MainComponent: React.FC = () => {
  return (
    <main className="flex flex-wrap justify-center items-start text-white">
      <OurPartners title="Our Partners" />
      <InstantAccess title="Instant Access" />
    </main>
  );
};

export default MainComponent;
