/**
 * This code was generated by Builder.io
 */
import React from "react";

interface AccessItemProps {
  imageSrc: string;
  title: string;
  subtitle?: string;
}

const AccessItem: React.FC<AccessItemProps> = ({
  imageSrc,
  title,
  subtitle,
}) => {
  return (
    <div className="flex flex-wrap gap-6 items-center w-full max-md:max-w-full mt-9">
      <img
        loading="lazy"
        src={imageSrc}
        alt=""
        className="object-contain shrink-0 self-stretch my-auto aspect-[1.03] w-[35px]"
      />
      <div className="flex flex-col rounded-none min-w-[240px] w-[275px]">
        <div className="mr-6 max-md:mr-2.5">{title}</div>
        {subtitle && <div>{subtitle}</div>}
      </div>
    </div>
  );
};

export default AccessItem;
