/**
 * This code was generated by Builder.io
 */
import React from "react";
import AccessItem from "./AccessItem";
import accessData from "./accessData.json";

interface InstantAccessProps {
  title: string;
}

const InstantAccess: React.FC<InstantAccessProps> = ({ title }) => {
  return (
    <section className="flex relative flex-1 shrink gap-10 items-start px-24 pt-24 basis-0 min-w-[240px] pb-[563px] max-md:px-5 max-md:pb-24 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/d59796ee9331eb5fc666e13e8a5b1ae6a6fcf24a1a3d2f5a13176a7e4507598d?placeholderIfAbsent=true&apiKey=82eec9096df64eb8b436c0dc64d15566"
        alt=""
        className="object-cover absolute inset-0 z-0 bg-center bg-cover aspect-[0.68] size-full max-md:max-w-full max-md:size-full"
      />
      <div className="flex z-0 flex-col flex-1 shrink basis-0 min-w-[240px] max-md:max-w-full">
        <h2 className="text-7xl font-light max-md:max-w-full max-md:text-4xl">
          {title}
        </h2>
        <div className="flex flex-col mt-32 w-full text-3xl max-md:mt-10 max-md:max-w-full">
          {accessData.map((item, index) => (
            <AccessItem key={index} {...item} />
          ))}
        </div>
      </div>
    </section>
  );
};

export default InstantAccess;
