/**
 * This code was generated by Builder.io
 */
import React from "react";

export type LegalNoticeProps = {
  legalText: string;
  trademarkText: string;
};

const LegalNotice: React.FC<LegalNoticeProps> = ({
  legalText,
  trademarkText,
}) => {
  return (
    <section className="flex flex-col lg:mt-16 w-full text-xs mt-10">
      <p className="max-w-full">{legalText}</p>
      <p className="mt-9 max-w-full">{trademarkText}</p>
    </section>
  );
};

export default LegalNotice;
